- name: get facts playbook
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: error handling block
    block:
      - name: debug
        debug:
          msg: "You will see failed tasks after this"

      - name: always failed
        command: /bin/false

      - name: unreachable debug
        debug:
          msg: "You won't see this message"
    rescue:
      - name: emergency debug
        debug:
          msg: "This task will be executed in case of block tasks failure"

      - name: also failed
        command: /bin/false
    always:
      - name: final debug
        debug:
          msg: "This task will always be executed"
