---
- name: job tags
  hosts: nodes
  become: true
  tasks:
    - name: task with prod tag
      debug:
        msg: "prod"
      tags:
        - prod

    - name: task with test tag
      debug:
        msg: "test"
      tags:
        - test
