---
- name: Install application
  hosts: nodes
  become: true
  vars:
    packages:
      - nginx
      - perl
  tasks:
    - name: Ensure that packages are installed
      yum:
        name: "{{ packages }}"
        state: installed
      tags:
        - install
