---
- name: Setup nginx webserver
  hosts: nodes
  tasks:
    - name: install and start nginx
      block:
        - name: Ensure nginx is installed
          yum:
            name: nginx
            state: present
        - name: Ensure nginx is started and enabled
          service:
            name: nginx
            state: started
            enabled: true
        - name: Populate service facts
          service_facts:
          register: service_facts_list
        - name: Ensure firewalld rule for nginx is enabled
          firewalld:
            port: 80/tcp
            permanent: true
            state: enabled
            immediate: true
          when: service_facts_list.ansible_facts.services["firewalld.service"].state == "running"
      # Тег относится ко всему блоку
      become: true
      tags:
        - webserver

    - name: Test connection without root priveleges
      uri:
        url: "http://{{ ansible_host }}"
        return_content: true
      register: webpage
      failed_when: webpage.status != 200
      connection: local
      tags:
        - webserver
        - check
