---
- name: include_role tasks
  hosts: localhost
  connection: local
  vars: 
    test_part: test
  tasks:
    - name: task before role
      debug:
        msg: "This task executes before roles' tasks"

    - name: dynamic role include_role
      include_role:
        name: "{{ test_part }}role"
      vars: 
        custom_var: 42
      tags: tagA

    - name: task after role
      debug:
        msg: "This task executes after roles' tasks" 
